import type { Metadata } from "next";
import { Geist, Geist_Mono, Kosugi_Maru } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const kosugiMaru = Kosugi_Maru({
	variable: "--font-kosugi-maru",
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html
			lang="en"
			className={`${geistSans.variable} ${geistMono.variable} ${kosugiMaru.variable}`}
		>
			<body className="antialiased">
				{children}
				<Toaster />
			</body>
		</html>
	);
}
